[tools]
claude = "latest"
helm = "latest"
jq = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
"npm:@salesforce/cli" = "latest"
pre-commit = "latest"
uv = "latest"

[hooks]
enter = "bash ./scripts/setup_project"
