# Salesforce-specific dependencies
# This allows you to create minimal images for each DAG
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "de-airflow-pipeline-salesforce"
version = "0.1.0"
description = "Salesforce extraction dependencies"
requires-python = ">=3.9"
dependencies = [
    "apache-airflow-providers-postgres==5.10.0",
    "apache-airflow-providers-salesforce==5.6.0",
    "pandas==2.1.4",
    "psycopg2-binary==2.9.9",
]

[tool.setuptools]
# Don't discover any packages - we're only using this for dependency installation
py-modules = []
